### ISSUE TITLE
how to use dronekit sitl  on raspberry pi 

### ISSUE THREAD

**Issue by keyurrakholiya** [dronekit/dronekit-sitl#95]
can i use dronekit sitl on raspberry pi with rasbian? or should i use ubuntu on raspberry pi? dronekit sitl is supported on R-pi or not?

thanks!

**Comment by LeonidasAntoniou** [comment]
The RPi has an ARM-based system architecture. The requirement for SITL to run in Linux is to have an Intel processor (x86 architecture) ([here](http://python.dronekit.io/develop/sitl_setup.html))

So, to cover your question, you cannot use dronekit sitl on RPi with raspbian or ubuntu or any linux distribution, since RPi does not have the proper processor (Intel x86).

What if you install Windows 10 on RPi and then trying to run sitl again? I have not tried it but it could be a possible solution if you want to run it so badly.

**Comment by hamishwillee** [comment]
To be more precise, DK-SITL does not **provide** binaries for ARM based architectures. You can build your own SITL binaries on RPi you can use DK-SITL to launch them. 

The main use case for DK-SITL is to run SITL on a host computer during development so that you can test your DK-Python code without running it on a real device. That development computer is far more likely to be an x86 desktop or laptop than an RPi/x86 based machine.

**Comment by fraseg** [comment]
Is there anywhere where I can get the build instructions to make a version for the pi?

**Comment by djdylex** [comment]
> Is there anywhere where I can get the build instructions to make a version for the pi?

As for building it, just need to compile the files using make. Does anyone know what to do after that? Like where do you put the binaries?

**Comment by Kanishk598** [comment]
@djdylex Were you able to do this properly?

**Comment by HefnySco** [comment]
you can compile ardupilot-sitl on arm easily using cross compile.
or just download ardupilot on RPI and compile it "make sitl" and you have an SITL running on RPI.
